[package]
name = "khid_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
futures-util = "0.3.31"
reqwest = {version = "0.12.24", features = ["stream"] }
scraper = "0.24.0"
tokio = { version = "1.48.0", features = ["full", "io-util"] }
urlencoding = "2.1.3"
